In [ ]:
import pandas as pd
import difflib
import numpy as np
from Similaridade import Bot_Semelhanca

In [2]:
#Exemplo

df = pd.DataFrame({
    'Produto': ['Caro', 'Casaaa', 'Biciceta', 'Aviaoo', 'Bicicleeta', 'celula','Panela','Celular','Moto'],
    'Categoria': ['Veículo', 'Residencial', 'Transporte', 'Transporte', 'Transporte','Tecnologia','Cozinha','Aparelho Eletrônico','Transporte'],
    'Cor': [np.nan,np.nan,np.nan,np.nan,np.nan,np.nan,np.nan,np.nan,np.nan]
})

df_consulta = pd.DataFrame({
    'Produto': ['Carro', 'Casa', 'Bicicleta','Bicicleta' ,'Avião', 'Celular'],
    'Categoria': ['Veículo', 'Residencial', 'Esporte','Esporte', 'Transporte', 'Tecnologia'],
    'Cor': ['Preto', 'Branco', 'Azul','Laranja' ,'Prata', 'Vermelho']
})

In [4]:
print('Data Frame')
display(df)
print('Data Frame Consulta')
display(df_consulta)

Data Frame

      Produto            Categoria  Cor
0        Caro              Veículo  NaN
1      Casaaa          Residencial  NaN
2    Biciceta           Transporte  NaN
3      Aviaoo           Transporte  NaN
4  Bicicleeta           Transporte  NaN
5      celula           Tecnologia  NaN
6      Panela              Cozinha  NaN
7     Celular  Aparelho Eletrônico  NaN
8        Moto           Transporte  NaN

Data Frame Consulta

     Produto    Categoria       Cor
0      Carro      Veículo     Preto
1       Casa  Residencial    Branco
2  Bicicleta      Esporte      Azul
3  Bicicleta      Esporte   Laranja
4      Avião   Transporte     Prata
5    Celular   Tecnologia  Vermelho

In [5]:
bot = Bot_Semelhanca(df,df_consulta)

# Classificando as Cores 
# A coluna1 e coluna2 não pode ter palavras np.nan

df_2 = bot.looping_semelhanca(coluna1='Produto',
                       coluna2='Categoria',
                       cutoff1=0.6,
                       cutoff2=0.6,
                       coluna_objetivo='Cor'
                       )

In [7]:
display(df_2)

,Produto,Categoria,Cor,Semelhança,Cor_Sugerida
0,Caro,Veículo,NaN,[Semelhante Produto e Categoria],[Preto]
1,Casaaa,Residencial,NaN,[Semelhante Produto e Categoria],[[Branco]]
2,Biciceta,Transporte,NaN,[Semelhante Produto e Categoria],"[[Azul, Laranja]]"
3,Aviaoo,Transporte,NaN,[Semelhante Produto e Categoria],[[Prata]]
4,Bicicleeta,Transporte,NaN,[Semelhante Produto e Categoria],"[[Azul, Laranja]]"
5,celula,Tecnologia,NaN,[Semelhante Produto e Categoria],[[Vermelho]]
6,Panela,Cozinha,NaN,[Nenhuma Semelhança],[Não Encontrada]
7,Celular,Aparelho Eletrônico,NaN,[Semelhante Produto],[[Vermelho]]
8,Moto,Transporte,NaN,"[Semelhante Categoria, Semelhante Categoria]","[[Prata], [Azul, Laranja]]"